services:
  web:
    volumes:
      - .:/app
    ports:
      - ${HOST_PORT}:${CONTAINER_PORT}
    command: uvicorn backend.main:app --reload --host 0.0.0.0 --port ${CONTAINER_PORT}

  db:
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - 3306:3306

volumes:
  dbdata:
