name: toolhunt-api

services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: mariadb
    image: mariadb:10.6
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
