name: toolhunt-api

services:
  fastapi-web:
    container_name: web
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/app
    ports:
      - ${HOST_PORT}:${CONTAINER_PORT}
    env_file:
      - .env
    command: uvicorn backend.main:app --reload --host 0.0.0.0 --port ${CONTAINER_PORT}
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: mariadb
    image: mariadb:10.6
    restart: always
    environment:
      - MARIADB_USER=user
      - MARIADB_PASSWORD=mypassword
      - MARIADB_ROOT_PASSWORD=rootpassword
      - MARIADB_DATABASE=web_dev
    volumes:
      - dbdata:/var/lib/mariadb/data/
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  dbdata:
