name: toolhunt-api

services:
  fastapi-web:
    container_name: web
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./backend:/app
    ports:
      - ${HOST_PORT}:${CONTAINER_PORT}
    env_file:
      - .env
    command: uvicorn main:app --reload --host 0.0.0.0 --port ${CONTAINER_PORT}
    depends_on:
      mariadb:
        condition: service_healthy

  mariadb:
    container_name: mariadb
    image: mariadb:10.6
    restart: always
    env_file:
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  mariadb_data:
